name = input("Digite o nome do jogo\n")
yearLaunch = int(input("Digite o ano de lançamento do jogo\n"))
gamePrice = float(input("Digite o preço do jogo\n"))
planIncluded = input("Está incluso no serviço mensal?\n")

print("Dados do jogo#####")
print('====================')
print("Nome do Jogo:", name)
print("Ano do Jogo:", yearLaunch)
print("Preço do Jogo:", gamePrice)
print("Está incluído no plano?", planIncluded)